definitions:
  config:
    /hst:hst/hst:configurations/myhippoproject/hst:pages/productslist:
      jcr:primaryType: hst:component
      hst:referencecomponent: hst:components/simplecomponent
      hst:template: homepage
